!//-------------------------------------------------------------------------
!//  This code was generated by cdf2c to read the netCDF data from the 
!//  RUCWindField netcdf file into memory.
!//  Shunxin did some modifications for adapting wish group purpose
!//-------------------------------------------------------------------------
!
!#include <netcdf.h>
!#include <ctime>
!#include "CONFIG_PARS.h"

      SUBROUTINE  read_RUCWindField(cp,u_Array,v_Array,flag)

       use CONFIG_PARS
       implicit none

       type (CCOUT_CONFIG_PARS) ,intent(in)  :: cp
       real,intent(out):: u_Array(cp.rucwindfield_ny,cp.rucwindfield_nx)
       real,intent(out):: v_Array(cp.rucwindfield_ny,cp.rucwindfield_nx)
       integer, intent(out) :: flag 

       real uArray(cp.rucwindfield_ny,cp.rucwindfield_nx)
       character*15  uArray_Units
       real vArray(cp.rucwindfield_ny,cp.rucwindfield_nx)
       character*15  vArray_Units
       character*12  TypeName
       character*9   DataType
       real          Latitude,Longitude,Height
       integer       Time
       real          FractionalTime
       character*31  attributes
       character*7   ExpiryInterval_unit
       character*3   ExpiryInterval_value
       character*13  Unit_unit
       character*15  Unit_value
       character*2   Level_unit
       character*3   Level_value
       character*13  scale_unit
       character     scale_value
       real    LatGridSpacing,LonGridSpacing,MissingData,RangeFolded
!       integer       fd, start2(MAX_NC_VARS),end2(MAX_NC_VARS)
       

!!!   //  This routine reads the data from RUC Wind Field file into memory.

       flag = 0

       RETURN
   
      END SUBROUTINE  read_RUCWindField


