#!/bin/sh

set -xa
echo `date`

thisver=$radar_ver

# #### 10/15/07 ##########################################
# SETUP 3-D RADAR REFLECTIVITY MOSAIC PROCESSING VARIABLES
# ########################################################

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export job=radar_reflectivity_ref2grb
export DATA=$DATAROOT/${job}.${pid}
mkdir -p $DATA
cd $DATA 

echo `date`
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=radarl2
export RUN=radar
export cycle=t${cyc}z
export SENDCOM=${SENDCOM:-YES}

export FIXgempak=$GEMTBL

export pgmout="OUTPUT.${pid}"

####################################
# Specify Execution Areas
####################################
#export HOMEradarl2=${HOMEradarl2:-${NWROOT}/radar_level2.${radar_ver}}
export EXECradar=$HOMEradarl2/exec
export PARMradar=$HOMEradarl2/parm
export SCRIPTSradar=$HOMEradarl2/scripts


mydate=`${NDATE}`
#mydate=${PDY}${cyc}
myyear=`echo $mydate | cut -c1-4`
mymon=`echo $mydate | cut -c5-6`
myday=`echo $mydate | cut -c7-8`
myhour=`echo $mydate | cut -c9-10`

#export COMOUT_REFprod=${COMOUT_REFprod:-$(compath.py -o ${NET}/${radarl2_ver}/${RUN}.$mydate)}
#export COMIN_SRCtank=${COMIN_SRCtank:-$(compath.py ${envir}/${NET}/${radarl2_ver}/SRCtank)}

# JY export BASEprod=$COMROOT
#export COMIN=${COMIN:-${COMROOT}/${NET}/${RUN}.$mydate}
#export SRCtank=${COMIN_SRCtank:-${COMROOT}/${NET}/SRCtank}
export COMIN=${COMIN:-$(compath.py ${envir}/${NET}/${radarl2_ver}/${RUN}.$mydate)}
export SRCtank=${COMIN_SRCtank:-$(compath.py ${envir}/${NET}/${radarl2_ver}/SRCtank)}

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. ./PDY

##############################
# Set COMOUT
##############################
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${radarl2_ver}/${RUN}.$PDY)}
mkdir -p $COMOUT

###############################################
# Convert binary 3D reflectivity mosaic to GRIB
###############################################
$SCRIPTSradar/exradar_reflectivity_ref2grb.sh
cat $pgmout

mydate=`$NDATE -48`
#mydate=`$NDATE -48 ${PDY}${cyc}`

COMINm1=${COMINm1:-${COMROOT}/${NET}/${RUN}.$mydate}
#COMINm1=${COMINm1:-$(compath.py ${envir}/${NET}/${radarl2_ver}/${RUN}.$mydate)}

rm -rf ${COMINm1}

KEEPDATA=${KEEPDATA:-NO}
if [ $KEEPDATA != "YES" ] ; then
    cd $DATAROOT
    rm -rf $DATA
fi

date
