#!/bin/sh

set -xa
echo `date`

thisver=$radar_ver

# #### 10/15/07 ##########################################
# SETUP 3-D RADAR REFLECTIVITY MOSAIC PROCESSING VARIABLES
# ########################################################

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export job=radar_reflectivity_ref2grb
#if [ $envir = prod ]
#then
#    DATAROOT=/tmpnwprd1
#else
#    DATAROOT=/tmpnwprd2
#fi
#export DATA=${DATA:-$DATAROOT/${job}.${pid}}
export DATA=$DATAROOT/${job}.${pid}
mkdir -p $DATA
cd $DATA 

echo `date`
export cycle=t${cyc}z

####################################
# Specify NET and RUN Name and model
####################################
export NET=radarl2
export RUN=radar
export cycle=t${cyc}z
export SENDCOM=${SENDCOM:-YES}

####################################
# Set up GEMPAK/NTRANS environment
####################################
#. /nwprod/gempak/.gempak
export FIXgempak=$GEMTBL


####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# Specify Execution Areas
####################################
export HOMEradarl2=${HOMEradarl2:-${NWROOT}/radar_level2.${radar_ver}}
export EXECradar=$HOMEradarl2/exec
export PARMradar=$HOMEradarl2/parm
export SCRIPTSradar=$HOMEradarl2/scripts

##############################
# Set up the UTILITIES
##############################
#export utilscript=/nwprod/util/ush
#export utilexec=/nwprod/util/exec

# JY mydate=`${NDATE}`
mydate=${PDY}${cyc}
myyear=`echo $mydate | cut -c1-4`
mymon=`echo $mydate | cut -c5-6`
myday=`echo $mydate | cut -c7-8`
myhour=`echo $mydate | cut -c9-10`

#export COMOUT_REFprod=${COMOUT_REFprod:-$(compath.py -o ${NET}/${radarl2_ver}/${RUN}.$mydate)}
#export COMIN_SRCtank=${COMIN_SRCtank:-$(compath.py ${envir}/${NET}/${radarl2_ver}/SRCtank)}

# JY export BASEprod=$COMROOT
#export COMIN=${COMIN:-${COMROOT}/${NET}/${RUN}.$mydate}
#export SRCtank=${COMIN_SRCtank:-${COMROOT}/${NET}/SRCtank}
export COMIN=${COMIN:-$(compath.py ${envir}/${NET}/${radarl2_ver}/${RUN}.$mydate)}
export SRCtank=${COMIN_SRCtank:-$(compath.py ${envir}/${NET}/${radarl2_ver}/SRCtank)}

##############################
# Run setup to initialize working directory and utility scripts
##############################
#sh $utilscript/setup.sh

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. ./PDY

##############################
# Set COMOUT
##############################
# JY export COMOUT=${COMOUT:-${COMROOT}/${NET}/${RUN}.$PDY}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${radarl2_ver}/${RUN}.$PDY)}
mkdir -p $COMOUT

###############################################
# Convert binary 3D reflectivity mosaic to GRIB
###############################################
$SCRIPTSradar/exradar_reflectivity_ref2grb.sh
cat $pgmout

# JY mydate=`$NDATE -48`
mydate=`$NDATE -48 ${PDY}${cyc}`

# JY COMINm1=${COMINm1:-${COMROOT}/${NET}/${RUN}.$mydate}
COMINm1=${COMINm1:-$(compath.py ${envir}/${NET}/${radarl2_ver}/${RUN}.$mydate)}

rm -rf ${COMINm1}

KEEPDATA=${KEEPDATA:-NO}
if [ $KEEPDATA != "YES" ] ; then
    cd $DATAROOT
    rm -rf $DATA
fi

date
